default_platform(:ios)

platform :ios do
  desc "TheMovie"
  lane :test do
    cocoapods
    run_tests(workspace: "TheMovie.xcworkspace",
              devices: ["iPhone 11"],
              scheme: "TheMovie")
  end
end